name: Image

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Get kind binary
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.9.0"
        skipClusterCreation: "true"

    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws        
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}        
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        token:    ${{ secrets.AWS_SESSION_TOKEN }}
      env:        
        AWS_REGION: us-east-1

    - name: Build image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: make build-image

    - name: Pull image
      if: startsWith(github.ref, 'refs/tags/v')
      run: make pull-image

    - name: Test image
      run: make test-image

    - name: Push image
      if: startsWith(github.ref, 'refs/tags/v') == false
      run: |
        make push-image

    - name: Promote image
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        make promote-image GITHUB_REF=$GITHUB_REF
